import type { Alert, AnalyticsData, MitreEntry, OverviewMetrics, SystemHealthData } from "@/types/dashboard";

/**
 * Data-access layer for the SOC dashboard. Every function here reads a
 * static JSON fixture exported directly from real Phase 4/5/6 pipeline
 * output (see `frontend/public/data/`, generated by a one-off script
 * against the actual verified pipeline runs) — not fabricated sample
 * data. Each function is `async` and shaped exactly like a future REST
 * call would be, so swapping the body for an `apiClient.get(...)` call
 * once the backend exposes these endpoints is a one-line change per
 * function; nothing above this layer (hooks, components) would need to
 * change at all.
 */

async function fetchJson<T>(path: string): Promise<T> {
  const response = await fetch(path);
  if (!response.ok) {
    throw new Error(`Failed to load ${path}: ${response.status} ${response.statusText}`);
  }
  return (await response.json()) as T;
}

export function getOverviewMetrics(): Promise<OverviewMetrics> {
  return fetchJson<OverviewMetrics>("/data/overview.json");
}

export function getAlerts(): Promise<Alert[]> {
  return fetchJson<Alert[]>("/data/alerts.json");
}

export function getAnalytics(): Promise<AnalyticsData> {
  return fetchJson<AnalyticsData>("/data/analytics.json");
}

export function getMitreRegistry(): Promise<MitreEntry[]> {
  return fetchJson<MitreEntry[]>("/data/mitre.json");
}

export function getSystemHealth(): Promise<SystemHealthData> {
  return fetchJson<SystemHealthData>("/data/system_health.json");
}